build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=phpunit-coverage'
                coverage:
                    file: 'phpunit-coverage'
                    format: 'clover'

filter:
    excluded_paths:
        - test/*